server_name               = "EBUSA_DEVELOPMENT"
environment               = "Development"
iam_sftp_role_name        = "EBUSA-Dev-SFTP-AccessRole"
iam_cloudwatch_role_name  = "EBUSA-SFTP-CloudWatch-Role"
s3_bucket_name            = "ebusa-dev-sftp-bucket1"
name_prefix               = "ebusa_dev_sftp_transfer_logs_"
cloudflare_api_token_path = "/ebusa/dev/sftp/cloudflare/api_token"
eb_sftp_dns_name          = "ebusa-sftp.dev"