server_name              = "EBUSA_DEVELOPMENT"
environment              = "Development"
iam_sftp_role_name       = "EBUSA-Dev-SFTP-AccessRole"
iam_cloudwatch_role_name = "EBUSA-SFTP-CloudWatch-Role"
s3_bucket_name           = "EBUSA-Dev-SFTP-Bucket1"
name_prefix              = "ebusa_dev_sftp_transfer_logs_"